// Generated by gencpp from file shape_msgs/Plane.msg
// DO NOT EDIT!


#ifndef SHAPE_MSGS_MESSAGE_PLANE_H
#define SHAPE_MSGS_MESSAGE_PLANE_H


#include <string>
#include <vector>
#include <memory>
#include <boost/shared_ptr.hpp>
#include <boost/array.hpp>


namespace shape_msgs
{
template <class ContainerAllocator>
struct Plane_
{
  typedef Plane_<ContainerAllocator> Type;

  Plane_()
    : coef()  {
      coef.assign(0.0);
  }
  Plane_(const ContainerAllocator& _alloc)
    : coef()  {
  (void)_alloc;
      coef.assign(0.0);
  }



   typedef boost::array<double, 4>  _coef_type;
  _coef_type coef;





  typedef boost::shared_ptr< ::shape_msgs::Plane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shape_msgs::Plane_<ContainerAllocator> const> ConstPtr;

}; // struct Plane_

typedef ::shape_msgs::Plane_<std::allocator<void> > Plane;

typedef boost::shared_ptr< ::shape_msgs::Plane > PlanePtr;
typedef boost::shared_ptr< ::shape_msgs::Plane const> PlaneConstPtr;

// constants requiring out of line definition




template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::shape_msgs::Plane_<ContainerAllocator1> & lhs, const ::shape_msgs::Plane_<ContainerAllocator2> & rhs)
{
  return lhs.coef == rhs.coef;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::shape_msgs::Plane_<ContainerAllocator1> & lhs, const ::shape_msgs::Plane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace shape_msgs



#endif // SHAPE_MSGS_MESSAGE_PLANE_H
